# Generated by Django 2.2.6 on 2019-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentaccount',
            name='loan_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
