# Generated by Django 2.2.6 on 2019-10-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment', '0002_auto_20191019_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentaccount',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
