# Generated by Django 2.2.5 on 2019-09-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('cac_number', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('bvn', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corpers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=20)),
                ('nysc_id', models.ImageField(upload_to='pics_upload')),
                ('validity_date', models.DateField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('bvn', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryEarners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('employment_status', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=100)),
                ('work_duration', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254)),
                ('monthly_salary', models.IntegerField()),
                ('monthly_salary_word', models.TextField(max_length=300, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('bvn', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StallionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('source_of_funds', models.CharField(max_length=100)),
                ('years_in_business', models.CharField(max_length=100)),
                ('monthly_turnover', models.IntegerField()),
                ('monthly_turnover_words', models.CharField(max_length=300)),
                ('purpose_of_loan', models.CharField(max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.CharField(max_length=100)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.BusinessOwners')),
            ],
        ),
        migrations.CreateModel(
            name='StallionSmart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_asset', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('invoice_value', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('salary_earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.SalaryEarners')),
            ],
        ),
        migrations.CreateModel(
            name='StallionLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('purpose_of_loan', models.TextField()),
                ('salary_earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.SalaryEarners')),
            ],
        ),
        migrations.CreateModel(
            name='StallionFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('fees_amount', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('salary_earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.SalaryEarners')),
            ],
        ),
        migrations.CreateModel(
            name='StallionAllowee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('purpose_of_loan', models.CharField(max_length=100)),
                ('package_list', models.CharField(max_length=100)),
                ('allowee', models.IntegerField()),
                ('corper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Corpers')),
            ],
        ),
        migrations.CreateModel(
            name='StallionAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('purpose_of_loan', models.TextField()),
                ('salary_earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.SalaryEarners')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_asset', models.CharField(max_length=100, null=True)),
                ('asset_name', models.CharField(max_length=100, null=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('invoice_value', models.IntegerField(null=True)),
                ('loan_amount', models.IntegerField(null=True)),
                ('purpose_of_loan', models.TextField(null=True)),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('education_level', models.CharField(max_length=100, null=True)),
                ('fees_amount', models.IntegerField(null=True)),
                ('business_type', models.CharField(max_length=100, null=True)),
                ('source_of_funds', models.CharField(max_length=100, null=True)),
                ('years_in_business', models.CharField(max_length=100, null=True)),
                ('monthly_turnover', models.IntegerField(null=True)),
                ('monthly_turnover_words', models.CharField(max_length=300, null=True)),
                ('loan_tenure', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.IntegerField(null=True)),
                ('purpose_of_loan', models.TextField(null=True)),
                ('loan_tenure', models.CharField(max_length=100, null=True)),
                ('package_list', models.CharField(max_length=200, null=True)),
                ('monthly_income', models.IntegerField(null=True)),
                ('loan_approval', models.BooleanField(default=None, null=True)),
                ('loan_disbursement', models.NullBooleanField()),
                ('loan_repayment', models.BooleanField(default=False)),
                ('disbursement_date', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwnersDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_director', models.CharField(max_length=100)),
                ('director_address', models.CharField(max_length=100)),
                ('means_of_identification', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_approval', models.NullBooleanField()),
                ('loan_disbursement', models.NullBooleanField()),
                ('loan_repayment', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
