# Generated by Django 2.2.6 on 2019-10-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='bank_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Document'),
        ),
    ]
