# Generated by Django 2.2.6 on 2019-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='loan_approval',
            field=models.BooleanField(null=True),
        ),
    ]
