# Generated by Django 2.2.6 on 2019-10-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='bank_statement',
            field=models.FileField(null=True, upload_to='', verbose_name='upload a valid bank statement '),
        ),
    ]
