# Generated by Django 2.2.6 on 2019-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20191026_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='monthly_salary',
            field=models.IntegerField(null=True),
        ),
    ]
