# Generated by Django 2.2.6 on 2019-10-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanaccount_bank_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='bank_statement',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='upload a valid bank statement'),
        ),
    ]
