# Generated by Django 2.2.6 on 2019-10-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanaccount_user_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanaccount',
            name='user_auth_code',
        ),
    ]
